### ISSUE TITLE
Set default meal choice and t-shirt to unset

### ISSUE THREAD

**Issue by sm6xmm** [EuroPython/epcon#1037]
I think it would be helpful for ordering if we knew how many tickets holders have actually bothered to select a meal choice and a t-shirt size. Now they default to omnivore and large, respectively, so the numbers for those are almost certainly too high.

If we default them to unset instead, we would know.

**Comment by malemburg** [comment]
Indeed. The defaults are making t-shirt and catering count estimates hard.

**Comment by rciorba** [comment]
I'll work on this one.

**Comment by rciorba** [comment]
What's the flow? Should this be close when dev/ep2020 gets merged to master, or should it be closed now?

**Comment by umgelurgel** [comment]
Issues get closed when merged - it's preferrable to include a `fixes #number` or `closes #number` so that the issue gets closed automatically, but it's not obligatory. Regarding branches, we don't use a `master` branch, we just use a different default branch per year, so `dev/ep2020` for the upcoming year.
