### ISSUE TITLE
Simplify dependencies setup to use one .in file

### ISSUE THREAD

**Issue by artcz** [EuroPython/epcon#1109]
We probably don't need the current three file system, which we introduced mostly to save some time on the builds – but on CI we actually build with the complete file anyway, so in practice it makes no difference.

Also, it would help with issues like this -> https://github.com/EuroPython/epcon/pull/1108 :)

**Comment by aramboi** [comment]
I don't think we should change our project structure just because some external tool does not know how to operate around it or does not allow us to configure these things. Also, I don't think it's ok to install dev dependencies in production.

**Comment by aramboi** [comment]
We already get security alerts here https://github.com/EuroPython/epcon/network/alerts so I think that should be enough. It's pretty easy to regenerate the requirements files and make a PR for this. 

We could just disable dependabot as it does not seem to help much in our case unless we use `Pipfile` which allows to have both dev and prod dependencies in the same file. The problem is that the `Pipfile` spec is very much in flux nowadays and the main tool for it `pipenv` break something with every other update. :/
