### ISSUE TITLE
Users need to adjust their profile to fill in the gender field

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1210]
We need logic which makes sure that the gender field is filled in for all attendees using the site for EP2020.

It's probably best to check the gender field for NULL after the user logs in and then redirect them to the profile editing page unconditionally with a note requesting update of the profile.

Since the gender field will be required, they will have to enter the field, so that we slowly end up with a consistent database again.

**Comment by umgelurgel** [comment]
So to clarify -> upon login, users with no gender information will be redirected to their profile update page if they haven't provided their gender information. They can update their profile there, they will be required to provide gender information in order to update the profile.

They're still able to navigate away from the profile update page and continue using the website as before, if they haven't updated their gender information.

Is that correct?

**Comment by malemburg** [comment]
On 02.03.2020 11:29, umgelurgel wrote:
> So to clarify -> upon login, users with no gender information will be
> redirected to their profile update page if they haven't provided their
> gender information. They can update their profile there, they will be
> required to provide gender information in order to update the profile.
> 
> They're still able to navigate away from the profile update page and
> continue using the website as before, if they haven't updated their
> gender information.
> 
> Is that correct?

Yes, we don't need a perfect solution, but the profile page and a note
to update the fields should definitely pop up.

-- 
Marc-Andre Lemburg
http://www.malemburg.com/
