### ISSUE TITLE
[ep-matrix] Embedding ep2021 webpages does not work

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1434]
Trying to do so via /addwidget https://ep2021.europython.eu/ result in this being shown:

![image](https://user-images.githubusercontent.com/6735498/122114117-372ff880-ce23-11eb-890e-bbae4518a280.png)

We will need to get this working, since we want to host the schedule overview widget on the EP website.

**Comment by fpierfed** [comment]
It is because we send this header
X-Frame-Options: SAMEORIGIN

when requesting https://ep2021.europython.eu:
:status: 200
Content-Type: text/html; charset=utf-8
Set-Cookie: csrftoken=XXX; expires=Thu, 16 Jun 2022 08:47:44 GMT; Max-Age=31449600; Path=/; SameSite=Lax
Content-Language: en
Expires: Thu, 17 Jun 2021 08:47:44 GMT
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Date: Thu, 17 Jun 2021 08:47:44 GMT
Content-Length: 46384
Vary: Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN
p3p: CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubdomains

**Comment by fpierfed** [comment]
We could investigate @xframe_options_exempt for selected views:
https://docs.djangoproject.com/en/2.2/ref/clickjacking/

**Comment by europython-society** [comment]
On 17.06.2021 10:48, Francesco Pierfederici wrote:
> It is because we send this header
> X-Frame-Options: SAMEORIGIN

Ok, so we'll have to relax that to allow *.europython.eu and
*.europython.io

-- 
Marc-Andre Lemburg
EuroPython Society Chair
http://www.europython-society.org/
http://www.malemburg.com/

**Comment by malemburg** [comment]
Probably better to do this for everything, not just individual views.

**Comment by fpierfed** [comment]
There are only two possible values for X-Frame-Options:
X-Frame-Options: DENY
X-Frame-Options: SAMEORIGIN
or disabled completely (i.e. not sending the header), which is bad on the whole website.

**Comment by malemburg** [comment]
Found that too just now: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

We should probably use this instead: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

**Comment by malemburg** [comment]
And then it's better to do this at the nginx level, not via Django.

**Comment by malemburg** [comment]
Content-Security-Policy: frame-src *.europython.eu *.europython.io;

should do the trick.

**Comment by malemburg** [comment]
In Django, we'd have to remove 'django.middleware.clickjacking.XFrameOptionsMiddleware',

**Comment by fpierfed** [comment]
I will give it a try on epstage

**Comment by fpierfed** [comment]
Maybe 
add_header Content-Security-Policy "default-src 'self'; font-src *;img-src *; script-src *; style-src *; frame-src *.europython.eu *.europython.io";
?
