### ISSUE TITLE
The google auth thing and more than one user with same email is a PITA!

### ISSUE THREAD

**Issue by alexsavio** [EuroPython/epcon#188]

**Comment by malemburg** [comment]
Indeed, but there's a simple work-around: you only have to deactivate one of the user accounts in the Django admin (see the "active" flag under "Permissions" of the user record). Be sure to deactivate the account without the tickets :-)

**Comment by alexsavio** [comment]
The problem goes further: if you assign a ticket to user with two accounts,
the ticket gets assigned to both user accounts. This causes that assigner
and assignees can't access their ticket page.

**Comment by alexsavio** [comment]
Not only that. In order to generate the badges. It can be not trivial to choose the user to pick the profile. I've seen users with social event ticket in one account and conference ticket in the other.

**Comment by malemburg** [comment]
In the call today we decided to drop the support for social account logins to keep things simple.

**Comment by malemburg** [comment]
See #215 and the discussion on the web-wg. Dropping support turned out to be a bad idea. In particualr, since it's not (easily) possible to turn a Google auth login account back into a password based one.

I've opened #218 to track the idea to prevent users from creating multiple accounts with the same email address.
