### ISSUE TITLE
Email address should be case insensitive

### ISSUE THREAD

**Issue by alexsavio** [EuroPython/epcon#393]
Some users have exactly the same email, but with camel case. Search for josep.

I think we should save and use emails only in small letters.

**Comment by matrixise** [comment]
add a validation in JS or backend ?

**Comment by alexsavio** [comment]
it's a backend thing. If someone registers or tries to login with an email address with a different case than what is in the database....we should be able to detect and say "hey, a user with your email already exists!"

**Comment by GadgetSteve** [comment]
There have been some issues on social media sites where the username/email was lower cased and this allowed spoofing because there were some unicode characters that had lower case versions that them self had lower case versions that were ascii characters. 

I would suggest lower casing any entered email addresses repeatedly until there are no changes.

**Comment by artcz** [comment]
added test for registration in https://github.com/EuroPython/epcon/pull/597
