### ISSUE TITLE
Turn session page into a generated page

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#506]
In previous years, I used to run a script for creating the session page list of of sessions (see https://ep2016.europython.eu/en/events/sessions/):

https://github.com/EuroPython/epcon/blob/ep2017/p3/management/commands/accepted_talks.py

For 2017, we should turn this into a view/tag based on a page template, so that we don't need manual intervention anymore. Probably best to just provide a tag to feed the data and have a CMS page render the page to stay more flexible.

One detail will be a bit tricky: we normally do not list the keynotes until we announce them. I guess we can manage this via the template or perhaps have a flag to disable showing keynotes until we have ll announced (they are listed on a separate page in more detail: https://ep2016.europython.eu/en/events/keynotes/).

**Comment by alanderex** [comment]
Regarding the keynotes: We can add them after the official announcement.
Of course it's be more elegant to have them in the system but hidden, it could be solved by introducing a new status for the session 'accepted (hidden)'. This would require an update on the speaker profile pages as well since all submissions are shown here.
