### ISSUE TITLE
CSS bug for table of contents

### ISSUE THREAD

**Issue by europython-society** [EuroPython/epcon#938]
The TOC overlays the content for window widths of 992px - 1200px:

![image](https://user-images.githubusercontent.com/10271045/57323198-a3e54e80-7105-11e9-93c2-bb62ecd64260.png)

**Comment by umgelurgel** [comment]
Affected url: https://ep2019.europython.eu/sponsor/packages/

**Comment by umgelurgel** [comment]
@artcz I tried playing around with the cms settings for the image in staging, but I didn't find a way to configure the image to scale to 100% width instead of a fixed width (current setting); the fact that the plugin we use for showing images has been unmaintained since 2016 doesn't help. Since the table as-is isn't that readable, I think reducing its width to 600 would be the fastest and cleanest solution. Alternatives would be a custom template for this page with custom css that overrides the one provided by `djangocms_filer`; what do you think?

**Comment by artcz** [comment]
I think we could try fixing this particular image manually, and in general look if there are better solutions available to deal with the automatic scaling for 2020.

**Comment by patrick91** [comment]
@umgelurgel we could add a css with:

```css
.page-selector img {
    max-width: 100%;
    height: auto;
}
```

this should fix the overflow problem :)

**Comment by umgelurgel** [comment]
@patrick91 that's a good shout, going to push a fix.
