### ISSUE TITLE
Trailing slash for registration page returns 404

### ISSUE THREAD

**Issue by econchick** [EuroPython/epcon#97]
Linked in the email by Marc-Andre [1](https://mail.python.org/pipermail/europython/2015-March/008629.html), trailing slash for registration page doesn't work:

Doesn't work: [https://ep2015.europython.eu/en/registration/](https://ep2015.europython.eu/en/registration/)
Does work: [https://ep2015.europython.eu/en/registration](https://ep2015.europython.eu/en/registration)

**Comment by d0ugal** [comment]
Gross :) Is that due to https://github.com/EuroPython/epcon/blob/develop/pycon/settings.py#L23 ?

**Comment by malemburg** [comment]
On 10.03.2015 17:22, Dougal Matthews wrote:

> Gross :) Is that due to https://github.com/EuroPython/epcon/blob/develop/pycon/settings.py#L23 ?

Probably, yes.

But this setting was added to fix another problem we had, so I'm
not sure we can simply remove it again.

## 

Marc-Andre Lemburg
Director
EuroPython Society
http://www.europython-society.org/

**Comment by d0ugal** [comment]
Looks like this was removed in #98 - I guess we should check for that other problem now :)

**Comment by malemburg** [comment]
That other problem was "fixed" by doing the redirect in nginx. It must have something to do with the i18n logic, since it caused the static files to get an /en/ prefix which then resulted in 404s for the static files - and only in DEBUG=False mode, not in DEBUG=True mode. Anyway, it only happens when running the site locally using manage.py runserver, so it's not a big deal.
